export const MAIN_ROUTE = '/'
export const BUY_TICKETS_ROUTE = '/buy-tickets'
export const EVENTS_ROUTE = '/events'
export const NEWS_ROUTE = '/news'
export const VIRTUAL_TOUR_ROUTE = '/3d-tour'
export const MUSEUM_PROJECTS_ROUTE = '/museum-projects'
export const QUIZ_ROUTE = '/quiz'

export const MUSEUM_ROUTE = '/museum'
export const ABOUT_MUSEUM_ROUTE = '/about-museum'
export const FONDS_MUSEUM_ROUTE = '/fonds-museum'
export const MEMORY_BOOK_ROUTE = '/memory-book'
export const RESEARCHERS_ROUTE = '/researchers'
export const MUSEUM_MAP_ROUTE = '/museum-map'
export const MUSEUM_HELPS_ROUTE = '/museum-helps'
export const CONTACTS_ROUTE = '/contacts'